export const SITE_CONFIG = {
  name: "Noel",
  fullName: "Noel Rio",
  title: "Noel — Full-Stack Web & Mobile Developer",
  description:
    "I build scalable web & mobile systems that simplify operations and grow organizations. Specializing in ERP, CMS, Finance Systems, and Custom Web Applications.",
  url: "https://me.berjalanbersama.com",
  ogImage: "/og-image.png",
  profileImage: "/images/profile/me.png",
  locale: "en",
  links: {
    whatsapp: "https://wa.me/6285735071598",
    email: "mailto:nrio2864@gmail.com",
    linkedin: "https://linkedin.com/in/noel-dev",
    github: "https://github.com/darkPigeonn",
  },
  // SEO keywords per language
  keywords: {
    en: [
      "full-stack developer",
      "web developer",
      "mobile developer",
      "freelance developer",
      "remote developer",
      "ERP developer",
      "CMS developer",
      "custom web application",
      "Flutter developer",
      "Next.js developer",
      "Vue developer",
      "React developer",
      "Node.js developer",
      "finance system developer",
      "school management system",
      "HR system developer",
      "payroll system",
      "WhatsApp bot developer",
      "API integration",
      "Indonesia developer",
    ],
    id: [
      "jasa pembuatan website",
      "jasa pembuatan aplikasi",
      "developer website",
      "developer aplikasi mobile",
      "freelance developer Indonesia",
      "pembuat ERP",
      "pembuat CMS",
      "aplikasi web custom",
      "developer Flutter",
      "developer Next.js",
      "developer Vue",
      "developer React",
      "developer Node.js",
      "sistem keuangan",
      "sistem manajemen sekolah",
      "sistem HR",
      "sistem payroll",
      "bot WhatsApp",
      "integrasi API",
      "jasa website murah",
      "programmer Indonesia",
    ],
  },
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Projects", href: "/projects" },
  { label: "Contact", href: "/contact" },
] as const;
